### ISSUE TITLE
Temperature display in the browser

### ISSUE THREAD

**Issue by tomas1515** [hendrychjan/valt-rpi#1]
Tell me how you made the temperature display in the browser?

**Comment by hendrychjan** [comment]
Sure!
I created a socket.io server in Node.js, then connected the python script on Rasp Pi to it (using socket.io client for python) and finally created a simple html page that subscribes changes from that Node.js server and displays it.
If you want, I can create a demo for you..

**Comment by tomas1515** [comment]
I was very happy if you make such a demo.

**Comment by hendrychjan** [comment]
Okay, will do

**Comment by hendrychjan** [comment]
Hi!
I finished the demo for you. Check it out at [https://github.com/hendrychjan/bmp280-realtime.git](https://github.com/hendrychjan/bmp280-realtime.git)
There is a simple installation and usage guide as well, I tried it and it worked swimmingly. 
Let me know what you think!

**Comment by tomas1515** [comment]
I did it a little differently. through the line
echo shell_exec('sudo python valt/sensor.py')"
This is the easiest way that was, I thought there was something more interesting.

**Comment by hendrychjan** [comment]
Oh, with php? I didn't think of that, cause I don't really use php, but yeah, it is the easiest way. I don't know if you can do the same in php, but with the way I did it, you can connect to the websocket stream from pretty much everywhere, like an Android app or even an extension in Gnome I suppose.

**Comment by tomas1515** [comment]
My raspberry is not in the general network. Only the internal network for this I do not particularly need the Internet. PHP includes two lines when, simple and convenient.
In addition to the temperature sensor, did you connect devices to raspberries?

**Comment by hendrychjan** [comment]
Yeah, well that's what I meant, you can connect to that web page from your local network, there is no way to connect from the outside. But you could do that using a VPN (zero-tier) for instance, then you could check the temperature at home even when you are away.

The downside of using php, if I'm not mistaken, is that you are sending the temperature data already wrapped in html - a whole web page. What I am doing, is providing a universal data stream, sending the data in a raw form, and it is put into the html and displayed only on the client side. If I wanted, I could connect to that raw data stream with another device and process it in a different way - maybe display it in an Android app instead of a web page (still working on the local network), or do something with it in an another Raspberry Pi.

The second downside of your approach is that you execute the whole script every time you want to get the current temperature. That means you have to run every line of code in that script over and over again - some of that code is not needed, like creating the variables, initializing the sensor etc - whatever needs to be executed just once. I run the script once, and it keeps just reading the temperature in an infinite loop, until I stop it.

Dont get me wrong though, your approach is absolutely fine - mostly aimed at simplicity, right?

To answer your second question, yes, I did connect things like buttons, LEDs, photo resistors, color sensors etc.

**Comment by hendrychjan** [comment]
I am going to close this issue, if that is ok?

**Comment by tomas1515** [comment]
Yes, everything is decided!
